version: '3'

services:
  nodeapp:
    image: programminghero/swarm-explore
    ports:
      - 3000:3000
    deploy:
      replicas: 15
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s
    networks:
      - balance

  proxy:
    image: nginx
    ports:
      - 80:80
    environment:
      - SERVER_IP=192.168.0.101
      - SERVER_PORT=3000
    depends_on:
      - nodeapp
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - balance
    volumes:
      - ./templates:/etc/nginx/templates

networks:
  balance:
    driver: overlay